"use client";

import Navbar from "@/components/Navbar";
import "../styles/globals.css";

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ArticleProvider } from "./contexts/ArticleContext";

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <Navbar />
        <ArticleProvider>
          <div className="container">
              {children}
          </div>
        </ArticleProvider>
      </body>
    </html>
  );
}
